import NavGroup from "@/components/nav-group";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { FaCircleUser, FaCreditCard, FaGraduationCap, FaHouse, FaInstagram, FaPercent, FaRegCircleQuestion, FaSketch } from "react-icons/fa6";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type AcademyLayoutProps = {
  children: ReactNode;
};

export default function AcademyLayout({ children }: AcademyLayoutProps) {
  return (
    <div className="flex flex-col md:flex-row w-full md:max-h-screen overflow-hidden">
      <nav className="flex flex-col justify-between bg-[#0b0b0b] w-full md:w-72 p-5 md:h-screen">
        <div className="flex flex-col">
          <Image
            src="/assets/logo-upstar.png"
            alt="Next.js logo"
            className="w-28 h-auto md:mb-8"
            width={579}
            height={153}
            priority
          />
          <NavGroup title="Overview" items={
            <div className="flex flex-col gap-1">
              <Link href='/dashboard' className="px-3 py-1 text-white flex gap-2 items-center hover:outline hover:outline-[#433744] hover:bg-gradient-to-b hover:from-[#332935] hover:to-[#453a46] hover:rounded-lg"><FaHouse color="#969498" /> Dashboard</Link>
              <Link href='/instagram-accounts' className="px-3 py-1 text-white flex gap-2 items-center hover:outline hover:outline-[#433744] hover:bg-gradient-to-b hover:from-[#332935] hover:to-[#453a46] hover:rounded-lg"><FaInstagram color="#969498" /> Comptes Instagram</Link>
            </div>
          } />
          <div className="border-t-2 border-dashed border-[#9694984c] my-5 hidden md:flex"></div>
          <NavGroup title="Settings" items={
            <div className="flex flex-col gap-1">
              <Link href='/account' className="px-3 py-1 text-white flex gap-2 items-center hover:outline hover:outline-[#433744] hover:bg-gradient-to-b hover:from-[#332935] hover:to-[#453a46] hover:rounded-lg"><FaCircleUser color="#969498" /> Account</Link>
              <Link href='/billing' className="px-3 py-1 text-white flex gap-2 items-center hover:outline hover:outline-[#433744] hover:bg-gradient-to-b hover:from-[#332935] hover:to-[#453a46] hover:rounded-lg"><FaCreditCard color="#969498" /> Billing</Link>
              <Link href='/plan' className="px-3 py-1 text-white flex gap-2 items-center hover:outline hover:outline-[#433744] hover:bg-gradient-to-b hover:from-[#332935] hover:to-[#453a46] hover:rounded-lg"><FaSketch color="#969498" /> Plan</Link>
            </div>
          } />
          <div className="border-t-2 border-dashed border-[#9694984c] my-5 hidden md:flex"></div>
          <NavGroup title="More" items={
            <div className="flex flex-col gap-1">
              <Link href='/account' className="px-3 py-1 text-white flex gap-2 items-center outline outline-[#433744] bg-gradient-to-b from-[#332935] to-[#453a46] rounded-lg"><FaGraduationCap color="#fff" /> Academy</Link>
              <Link href='/billing' className="px-3 py-1 text-white flex gap-2 items-center hover:outline hover:outline-[#433744] hover:bg-gradient-to-b hover:from-[#332935] hover:to-[#453a46] hover:rounded-lg"><FaPercent color="#969498" /> Affiliation</Link>
              <Link href='/plan' className="px-3 py-1 text-white flex gap-2 items-center hover:outline hover:outline-[#433744] hover:bg-gradient-to-b hover:from-[#332935] hover:to-[#453a46] hover:rounded-lg"><FaRegCircleQuestion color="#969498" /> Support</Link>
            </div>
          } />
        </div>
        <Link href="/academy/course-1" className="hidden md:flex bg-gradient-to-r from-[#a46ef3] via-[#ff77ac] to-[#fcaa74] text-white px-3 py-2 rounded-lg text-center justify-center items-center text-sm">Upgrade to Expert</Link>
      </nav>
      <div className="flex flex-col w-full">
        <div className="bg-white px-7 py-5 border-solid border border-[#e5e5e5]">
          <p className="font-medium">Academy</p>
        </div>
        <div className="bg-[#fbfbfb] w-full h-full overflow-y-auto">{children}</div>
      </div>
    </div>
  );
}
